# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Alta', 'AT'), ('Normal', 'NR'), ('Baja', 'BJ')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
