# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='prioridad',
            field=models.CharField(choices=[('AT', 'Alta'), ('NR', 'Normal'), ('BJ', 'Baja')], max_length=30),
        ),
    ]
